name = "QuantizedNoise"
uuid = "73f4e83f-5129-41ef-a7bf-22ba0654e29d"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
